key1_new_array:
  - 11
  - 12
  - 13
key2_map:
  key2_map_new_1_string: ___ip_address___
  key2_map_2_map:
    key2_map_2_map_1_string: key2_map_2_map_1_string
    key2_map_2_map_2_number: 222
    key2_map_2_map_3_new_array:
      - 2211
      - 2222
      - 2233
    key2_map_2_map_4_map:
      key2_map_2_map_4_map_1_string: key2_map_2_map_4_map_string
      key2_map_2_map_4_map_2_new_number: 2241
      key2_map_2_map_4_map_3_array:
        - 2241
        - 2242
        - 2243
key3_string: key3_string
key4_new_number: 41
key5_array_map:
  - key5_array_map_1:
      key5_array_map_1_string_1: ___project_name___
      key5_array_map_1_number_2: 1211
      key5_array_map_1_string_3: ___random32___
  - key5_array_map_2:
      key5_array_map_2_string_1: ___ip_address___
      key5_array_map_2_number_2: 1211
      key5_array_map_2_string_3: ___random___
      key5_array_map_2_string_4: