server4:
  username4: "username41"
  pass4:

server2:
  url2: "username21"

server10:
  url1: "{{random}}"
  url2: "{{random8}}"
  url3: "{{random32}}"
  url4: "{{random64}}"
  url5: "root:123123@tcp({{ip_address}}:3306)/root?charset=utf8mb4&parseTime=True&loc=Local"
  url6: "{{project_name}}"
